### ISSUE TITLE
Override default value for $dir - html[dir="rtl"]

### ISSUE THREAD

**Issue by llioor** [tysonmatanich/directional-scss#3]
Hi,
I'm trying to change the $dir parameter by the html "dir" attribute without success.
I want to work with one css file and not with an css-rtl so what is the right way to handle it?

Wanted situation:
// Override default value for $dir in directional.scss
html[dir="rtl"] {
  $dir: rtl;
}

**Comment by tysonmatanich** [comment]
There isn't a great way of doing it with a single CSS file otherwise you are serving duplicate styles to the client. Once you have things setup, maintaining the second file should should be almost no work as it should just auto compile for you. Also your approach above is invalid as you can't really set Sass variables based on CSS selectors since the Sass is compiled to CSS on the server and is independent of the HTML markup.
